# Site settings
title: No Person Shall 14:3
email: info@nopersonshall.com
description:  have engaged in insurrection or rebellion against the United States
baseurl: "" # the subpath of your site, e.g. /blog/
url: "nopersonshall.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
